# Generated by Django 3.0.5 on 2020-05-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('ingredients_text', models.CharField(max_length=500)),
                ('allergens', models.CharField(max_length=500)),
                ('serving_size', models.CharField(max_length=100)),
                ('fat_100g', models.DecimalField(blank=True, decimal_places=4, max_digits=8)),
                ('cholesterol_100g', models.DecimalField(blank=True, decimal_places=4, max_digits=8)),
                ('carbohydrates_100g', models.DecimalField(blank=True, decimal_places=4, max_digits=8)),
                ('sugars_100g', models.DecimalField(blank=True, decimal_places=4, max_digits=8)),
                ('fiber_100g', models.DecimalField(blank=True, decimal_places=4, max_digits=8)),
                ('proteins_100g', models.DecimalField(blank=True, decimal_places=4, max_digits=8)),
                ('salt_100g', models.DecimalField(blank=True, decimal_places=4, max_digits=8)),
                ('sodium_100g', models.DecimalField(blank=True, decimal_places=4, max_digits=8)),
                ('alcohol_100g', models.DecimalField(blank=True, decimal_places=4, max_digits=8)),
            ],
        ),
    ]
