# Generated by Django 3.0.5 on 2020-05-07 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlucoseTracker',
            new_name='FoodItem',
        ),
    ]
