# Generated by Django 3.0.5 on 2020-05-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200507_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='allergens',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='ingredients_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='product_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='serving_size',
            field=models.TextField(blank=True),
        ),
    ]
