# Generated by Django 3.0.5 on 2020-05-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200507_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='alcohol_100g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='carbohydrates_100g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='cholesterol_100g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fat_100g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fiber_100g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='proteins_100g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='salt_100g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='sodium_100g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='sugars_100g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
    ]
