# Generated by Django 3.0.5 on 2020-05-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='hbA1c',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
