# Generated by Django 3.0.5 on 2020-05-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200511_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='fasting_plasma_glucose',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='h2_plasma_glucose',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8),
        ),
    ]
